<?php

declare(strict_types=1);

const SWEPT_SNIFFS = [
    'CleanCode.Arrays.ArrayAccessors',
    'CleanCode.Arrays.DuplicatedArrayKey',
    'CleanCode.Classes.ClassDeclaration',
    'CleanCode.Classes.DisallowStaticMembers',
    'CleanCode.Classes.DisallowTypeIntrospection',
    'CleanCode.Classes.ExcessiveClassLength',
    'CleanCode.Classes.NewWithoutParentheses',
    'CleanCode.Classes.TooManyPublicMethods',
    'CleanCode.ClearCode.OneThoughtPerLine',
    'CleanCode.CodeSize.TooManyMethods',
    'CleanCode.CodeStyle.NoFormatterDirectives',
    'CleanCode.Collections.OnlyUseCollectionMethods',
    'CleanCode.Conditionals.DisallowElse',
    'CleanCode.Conditionals.DisallowListAssignmentInCondition',
    'CleanCode.Conditionals.DisallowNestedTernary',
    'CleanCode.Conditionals.OneConditionPerLine',
    'CleanCode.Constructors.NoLogic',
    'CleanCode.ControlStructures.DisallowCountInLoopExpression',
    'CleanCode.ControlStructures.DisallowExitExpression',
    'CleanCode.Controversial.Superglobals',
    'CleanCode.DeadCode.UnusedFormalParameter',
    'CleanCode.DeadCode.UnusedPrivateElements',
    'CleanCode.Debug.DisallowDebugFunctions',
    'CleanCode.Functions.DisallowBooleanArgumentFlag',
    'CleanCode.Functions.ExcessiveMethodLength',
    'CleanCode.Functions.ExcessiveParameterList',
    'CleanCode.Indentation.LogicalGroupings',
    'CleanCode.Livewire.ComponentMarkup',
    'CleanCode.Methods.DeclaredParameters',
    'CleanCode.Methods.NoNullArguments',
    'CleanCode.Metrics.CouplingBetweenObjects',
    'CleanCode.Metrics.CyclomaticComplexity',
    'CleanCode.Metrics.DepthOfInheritance',
    'CleanCode.Metrics.ExcessiveClassComplexity',
    'CleanCode.Metrics.ExcessivePublicCount',
    'CleanCode.Metrics.MethodNestingLevel',
    'CleanCode.Metrics.NPathComplexity',
    'CleanCode.Metrics.NumberOfChildren',
    'CleanCode.Metrics.TooManyFields',
    'CleanCode.Models.MemberOrdering',
    'CleanCode.Naming.BooleanGetMethodName',
    'CleanCode.Naming.LongClassName',
    'CleanCode.Naming.LongVariable',
    'CleanCode.Naming.ModelNamingConventions',
    'CleanCode.Naming.RedundantNamespaceSuffix',
    'CleanCode.Naming.ShortClassName',
    'CleanCode.Naming.ShortMethodName',
    'CleanCode.Naming.ShortVariable',
    'CleanCode.Operators.BinaryOperatorSpacing',
    'CleanCode.Operators.BooleanOperatorSpacing',
    'CleanCode.Operators.ManipulationOperatorPlacement',
    'CleanCode.Operators.NotOperatorSpacing',
    'CleanCode.Operators.OperatorLineBreak',
    'CleanCode.Routes.ApiControllerNamespace',
    'CleanCode.Routes.DisallowClosureRoutes',
    'CleanCode.Strings.DisallowNowdoc',
    'CleanCode.Strings.EscapeNestedQuotes',
    'CleanCode.Strings.HtmlAttributeQuotes',
    'CleanCode.Strings.MultilineStrings',
    'CleanCode.Strings.RequireHeredocForStructuredText',
    'CleanCode.Strings.RequireStringInterpolation',
    'CleanCode.WhiteSpace.BlankLines',
    'CleanCode.WhiteSpace.MultiLineStatementIndent',
    'CleanCode.WhiteSpace.PassiveOperatorSpacing',
    'CleanCode.WhiteSpace.ScopeClosingBrace',
    'Generic.CodeAnalysis.AssignmentInCondition',
    'Generic.ControlStructures.InlineControlStructure',
    'Generic.Files.LineLength',
    'Generic.NamingConventions.ConstructorName',
    'Generic.PHP.DiscourageGoto',
    'Generic.PHP.NoSilencedErrors',
    'SlevomatCodingStandard.Classes.RequireConstructorPropertyPromotion',
    'SlevomatCodingStandard.Exceptions.ReferenceThrowableOnly',
    'SlevomatCodingStandard.Exceptions.RequireNonCapturingCatch',
    'SlevomatCodingStandard.Namespaces.UnusedUses',
    'Squiz.PHP.DisallowMultipleAssignments',
    'Squiz.PHP.Eval',
    'VariableAnalysis.CodeAnalysis.VariableAnalysis',
];

const SWEPT_WARNING_SNIFFS = [
    'CleanCode.Arrays.ConvertToCollection',
    'CleanCode.Classes.DisallowConstructorInstantiation',
    'CleanCode.ClearCode.ActionSingleEntryPoint',
    'CleanCode.ClearCode.JunkDrawerNamespace',
    'CleanCode.ClearCode.SectionComment',
    'CleanCode.Commenting.DebtMarkers',
    'CleanCode.Conditionals.AvoidConditionals',
    'CleanCode.Conditionals.CombinableConditions',
    'CleanCode.Conditionals.MappingArrayCandidate',
    'CleanCode.Conditionals.TypeDiscriminatorDispatch',
    'CleanCode.Constructors.DisallowCombinedConstructor',
    'CleanCode.Constructors.PrimaryConstructorDelegation',
    'CleanCode.Controllers.ManualModelResolution',
    'CleanCode.Controllers.NoCustomActions',
    'CleanCode.Models.DisallowAlwaysOnEagerLoading',
    'CleanCode.Models.ModelMagicMethodLocation',
    'CleanCode.Models.RequireLazyLoadingPrevention',
    'CleanCode.Naming.ActionMethodReturn',
    'CleanCode.Naming.DisallowMagicNumbers',
    'CleanCode.Pattern.AvoidDuplicateCodeBlocks',
    'CleanCode.Pattern.DisallowRepositoryClasses',
    'CleanCode.Pattern.ThrowOnlyMethodOverride',
    'CleanCode.Pattern.TooManyInterfaceMethods',
    'CleanCode.Testing.NoFirstPartyMocks',
    'CleanCode.Testing.NoReflectionAccess',
    'CleanCode.Testing.TestSuiteNamespace',
    'Generic.Commenting.Fixme',
    'Generic.Commenting.Todo',
];

const AUTOFIXABLE_SNIFFS = [
    'CleanCode.Arrays.ArrayAccessors',
    'CleanCode.Classes.ClassDeclaration',
    'CleanCode.Classes.NewWithoutParentheses',
    'CleanCode.ClearCode.OneThoughtPerLine',
    'CleanCode.Collections.OnlyUseCollectionMethods',
    'CleanCode.Conditionals.DisallowElse',
    'CleanCode.Conditionals.OneConditionPerLine',
    'CleanCode.Indentation.LogicalGroupings',
    'CleanCode.Methods.NoNullArguments',
    'CleanCode.Operators.BinaryOperatorSpacing',
    'CleanCode.Operators.BooleanOperatorSpacing',
    'CleanCode.Operators.ManipulationOperatorPlacement',
    'CleanCode.Operators.NotOperatorSpacing',
    'CleanCode.Operators.OperatorLineBreak',
    'CleanCode.Strings.DisallowNowdoc',
    'CleanCode.Strings.EscapeNestedQuotes',
    'CleanCode.Strings.HtmlAttributeQuotes',
    'CleanCode.Strings.MultilineStrings',
    'CleanCode.Strings.RequireStringInterpolation',
    'CleanCode.WhiteSpace.BlankLines',
    'CleanCode.WhiteSpace.MultiLineStatementIndent',
    'CleanCode.WhiteSpace.PassiveOperatorSpacing',
    'CleanCode.WhiteSpace.ScopeClosingBrace',
    'Generic.ControlStructures.InlineControlStructure',
    'SlevomatCodingStandard.Classes.RequireConstructorPropertyPromotion',
    'SlevomatCodingStandard.Exceptions.ReferenceThrowableOnly',
    'SlevomatCodingStandard.Exceptions.RequireNonCapturingCatch',
    'SlevomatCodingStandard.Namespaces.UnusedUses',
];

const SHIPPED_SMOKE_EXCLUSIONS = [
    'CleanCode.Metrics.CyclomaticComplexity',
];

function shippedSmokeSniffs(array $swept): array
{
    $custom = array_filter($swept, static fn (string $code): bool => str_starts_with($code, 'CleanCode.'));

    return array_values(array_diff($custom, SHIPPED_SMOKE_EXCLUSIONS));
}

function expectedFailingStatus(string $sniffCode, array $messages): int
{
    if (in_array($sniffCode, AUTOFIXABLE_SNIFFS, true) === false) {
        return 2;
    }

    return in_array(false, array_column($messages, 'fixable'), true) === true ? 3 : 1;
}
